version: '3.8'

services:
  backend:
    build:
      context: .
      args:
        - NODE_ENV=$NODE_ENV
    restart: always
    env_file: ./.env
    ports:
      - $BACKEND_LOCAL_PORT:$PORT
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
      - ICONS_TABLE_NAME=$ICONS_TABLE_NAME
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_REGION=$AWS_REGION
